version: '3.8'

services:
  file-organizer:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - GEMINI_API_KEY=AIzaSyDGGN9AwTvfMKRS506CeprfiBXjCxv8nPQ
      - DOWNLOADS_PATH=/app/downloads
    restart: unless-stopped
